language: node_js
node_js:
- '8'
services:
- mongodb
- redis-server
before_script:
- mongo prello_test --eval 'db.createUser({user:"prello",pwd:"prello",roles:["readWrite"]});'
script: cd Server && npm install && npm test
before_install:
- openssl aes-256-cbc -K $encrypted_33cf719da424_key -iv $encrypted_33cf719da424_iv
  -in deploy_rsa.enc -out deploy_rsa -d
