language: node_js
node_js:
    - "8"
services:
    - mongodb
    - redis-server
before_script:
    - mongo prello_test --eval 'db.createUser({user:"prello",pwd:"prello",roles:["readWrite"]});'
script: cd Server && npm install && npm test 
